### ISSUE TITLE
No rule to make target 'menuconfig'

### ISSUE THREAD

**Issue by IzzuddinYussof** [EDLLT/WSL2-Linux-Kernel#3]
Hi,

I have two questions for now

1) When it said to put the driver inside the folder, may I know how to get the driver? For example mine is using the chipset Realtek RTL8812AU, and the driver format that I have is 8812au.ko. Where do I get one with those Kconfig file? 

And I realise that there are already rtl8xxxu folder inside the realtek folder and both the Kconfig and Makefile already pointed to the relevant files, does that mean I don't have to do anything for those steps anymore?

Sorry if the question sounds too misleading, I'm still learning

2) When trying to get into menuconfig, it comes out with an error:

make: *** No rule to make target 'menuconfig'.  Stop.

What should I do?

Really appreciate your reply. Thank you

**Comment by sxlekk** [comment]
I have the same issue can someone help?

**Comment by EDLLT** [comment]
> When it said to put the driver inside the folder, may I know how to get the driver?

You are not supposed to place a .ko file there, but rather a folder which contains a makefile
You can find one from GitHub simply by searching "(driver name) GitHub" on Google

Here's one that I found, try using this driver instead
[RTL8812AU github](https://github.com/aircrack-ng/rtl8812au)

**Comment by Millou1** [comment]
it works for you now? because for me still not
